aws cicd test

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -12,6 +12,12 @@ phases:
     commands:
       - echo Build started on `date`
       - sh lambda_deploy.sh
+      - echo "$?"
+      - |
+        if [ $? -ne 0 ]; then
+          echo "Lambda Deploy Error. FunctionName=${FUNC_NAME}."
+          exit 2
+        fi
       - sleep 10
   post_build:
     on-failure: ABORT
